CMakeLists.txt: fix linking with ld
Fix for the error below:
ld: liblldELF.a(OutputSections.cpp.o): undefined reference to symbol 'deflate'
ld: libz.so.1: error adding symbols: DSO missing from command line

ld recently changed to only link with explicitly defined targets