fix build on Ubuntu
It appears that Ubuntu (and IIRC Debian) removed KFreeBSD from llvm

[1/3] Building CXX object CMakeFiles/zig_cpp.dir/src/zig_llvm.cpp.o
FAILED: CMakeFiles/zig_cpp.dir/src/zig_llvm.cpp.o
/usr/bin/c++   -I../deps/lld/include -I/usr/lib/llvm-7/include -I../deps/SoftFloat-3e/source/include -I../ -I. -I../src -g   -std=c++11 -Werror -Wall -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -D_GNU_SOURCE -fno-exceptions -fno-rtti  -Werror=strict-prototypes -Werror=old-style-definition -Werror=type-limits -Wno-missing-braces -MD -MT CMakeFiles/zig_cpp.dir/src/zig_llvm.cpp.o -MF CMakeFiles/zig_cpp.dir/src/zig_llvm.cpp.o.d -o CMakeFiles/zig_cpp.dir/src/zig_llvm.cpp.o -c ../src/zig_llvm.cpp
../src/zig_llvm.cpp:1032:59: error: ‘KFreeBSD’ is not a member of ‘llvm::Triple’
 static_assert((Triple::OSType)ZigLLVM_KFreeBSD == Triple::KFreeBSD, "");
                                                           ^~~~~~~~
ninja: build stopped: subcommand failed.