std.Target: Run update_cpu_features against the LLVM version used by CI
In #20975, update_cpu_features was run against LLVM 18.1.8, but the CI uses 18.1.5, and unaligned-scalar-mem was added in LLVM 18.1.6, so the CI was outputting:

```
+- test-link
   +- link_test_cases
      +- test-elf
         +- test-elf-linking-c-riscv64-linux.4.19...6.10.3-musl-Debug-llvm-no-lld
            +- CheckObject
               +- zig build-exe test Debug riscv64-linux-musl failure
error: '-unaligned-scalar-mem' is not a recognized feature for this target (ignoring feature)
'-unaligned-scalar-mem' is not a recognized feature for this target (ignoring feature)
'-unaligned-scalar-mem' is not a recognized feature for this target (ignoring feature)
```