fix undefined symbol errors
After commit fd75e73e ("add f16 type"), the Ubuntu CI machine started
failing with the following link-time errors:

		lld: error: undefined symbol: __gnu_f2h_ieee
		>>> referenced by math.zig:9(/home/travis/build/ziglang/zig/test/cases/math.zig:9)
		>>>               ./zig-cache/test.o:(testDivision)

		lld: error: undefined symbol: __gnu_h2f_ieee
		>>> referenced by math.zig:9(/home/travis/build/ziglang/zig/test/cases/math.zig:9)
		>>>               ./zig-cache/test.o:(testDivision)

Export the symbols unconditionally except on MacOS.  This follows the
logic in LLVM's lib/CodeGen/TargetLoweringBase.cpp.

Don't export the symbols when testing on Windows because it results in
duplicate symbol errors when linking the compiler_rt tests (but not
other tests.)