explicit parentheses to resolve issue #8159
When an if statement in a while loop with no parentheses is parsed it gives: 
./forifassign.zig:1036:46: error: invalid left-hand side to assignment
        while (i < @as(c_int, 5)) : (i += 1) if (i == @as(c_int, 0)) i = 10;

With the explicit parentheses it should give:
        while (i < @as(c_int, 5)) : (i += 1) (if (i == @as(c_int, 0)) i = 10;)

So the ir can be read correctly.